---
name: static-code-analysis
on:
  push:
    branches: main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Sonarcloud:
    uses: firebolt-analytics/gha-workflows/.github/workflows/reusable-sonarcloud.yaml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
